export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_ADD_INCREMENT = 'CART_ADD_INCREMENT'
export const CART_ADD_DECREMENT = 'CART_ADD_DECREMENT'

export const CART_TOGGLE = 'CART_TOGGLE'
export const CART_TOGGLE_OPEN = 'CART_TOGGLE_OPEN'
export const CART_TOGGLE_CLOSE = 'CART_TOGGLE_CLOSE'

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'