//PRODUCT LIST
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

//PRODUCT LASTEST
export const PRODUCT_LATEST_REQUEST = "PRODUCT_LATEST_REQUEST";
export const PRODUCT_LATEST_SUCCESS = "PRODUCT_LATEST_SUCCESS";
export const PRODUCT_LATEST_FAIL = "PRODUCT_LATEST_FAIL";

//PRODUCT BEST SELLER
export const PRODUCT_BESTSELLER_REQUEST = "PRODUCT_BESTSELLER_REQUEST";
export const PRODUCT_BESTSELLER_SUCCESS = "PRODUCT_BESTSELLER_SUCCESS";
export const PRODUCT_BESTSELLER_FAIL = "PRODUCT_BESTSELLER_FAIL";

//PRODUCT CATEGORY
export const PRODUCT_CATEGORY_LIST_REQUEST = "PRODUCT_CATEGORY_LIST_REQUEST";
export const PRODUCT_CATEGORY_LIST_SUCCESS = "PRODUCT_CATEGORY_LIST_SUCCESS";
export const PRODUCT_CATEGORY_LIST_FAIL = "PRODUCT_CATEGORY_LIST_FAIL";

//PRODUCT CREATED
export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

//PRODUCT DETAILS
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

//PRODUCT UPDATE
export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

//PRODUCT DELETE
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET'

// PRODUCT FILTER
export const PRODUCT_FILTER_SUCCESS = 'PRODUCT_FILTER_SUCCESS'
export const PRODUCT_FILTER = 'PRODUCT_FILTER'
